### ISSUE TITLE
Anonymous session

### ISSUE THREAD

**Issue by AntoineSIMTEK** [ComputationalMechanics/TopoBank#164]
At login, the user should be presented with the choice to login via ORCID or anonymously. For an anonymous session, all data will be deleted upon logout (or when the session expires).

**Comment by mcrot** [comment]
Okay, this can be implemented after #317.

**Comment by mcrot** [comment]
How should the landing page look like here? So far, we have some statistics:
![grafik](https://user-images.githubusercontent.com/9113541/92101316-3c184400-eddd-11ea-823a-a3a8abb1307a.png)

My suggestion is to keep this and to add the "Select" tab as for normal users.
Then the anonymous user can click on "Select" or on the blue/red/yellow box in order to get to the "Select" tab.
![grafik](https://user-images.githubusercontent.com/9113541/92102065-5d2d6480-edde-11ea-8f67-fa0e2214366f.png)

What do you think @pastewka , @AntoineSIMTEK ?

Effectively, the anonymous user should be able to do everything as a normal user,
except

- creating new surfaces
- creating/uploading new topographies
- editing and deleting surfaces+topographies
- publishing and sharing

I'm not sure, whether we should allow to submit new analyses e.g. for contact mechanics - 
it would be easy to create many, many jobs without being authenticated.

**Comment by pastewka** [comment]
The GUI looks good!

However, the anonymous user should not be able to create surfaces and upload topographies. We would then need a user that is tied to a browser session and to remove the uploaded data after the session expires. If we allow the submission of analyses, wouldn't that interfere with other users that are anonymously browsing the site. If not, I think we could allow it.

**Comment by pastewka** [comment]
I think the graying out is a good idea, if this is simple. Also not allowing calculations is probably a good idea. Which analysis will then be shown? I guess one with default parameters?

**Comment by mcrot** [comment]
If there are no analyses yet for a user, the analyses is requested automatically with the default parameters.
Since the anonymous user should not be able to request new analyses with differing parameters, there
should be only ones with default parameters (and only generated once).

**Comment by mcrot** [comment]
Do we need some indicator on each page to make clear that the user uses an anonymous session?

For example, there could be a button in the navigation bar like this:

![image](https://user-images.githubusercontent.com/9113541/92605110-9c155b80-f2b1-11ea-9738-e98bfe907b14.png)

Or as alternative a horizontal bar like this:

![image](https://user-images.githubusercontent.com/9113541/92606049-cd425b80-f2b2-11ea-937e-6a43cff65ff4.png)

However, this takes more place than the button in the navigation bar.
What do you think @pastewka, @tdbjacobs, @AntoineSIMTEK ? Is this helpful?

Both variants would also be visible for anyone who arrives on the app because of clicking on a publication link.

**Comment by pastewka** [comment]
I think I prefer the button in the navigation bar. It is less obstructive and the navigation bar is mainly empty anyway.
