### ISSUE TITLE
Average data in analysis plot

### ISSUE THREAD

**Issue by pastewka** [ComputationalMechanics/TopoBank#365]
Add a button saying "average" that takes the average of all data and shows it superimposed on top of the individual data.

**Comment by mcrot** [comment]
From the related paper
> The combined PSD represents the arithmetic average of all of the
individual PSDs that were computed from each topography
measurement. Because random surfaces are often described as
Gaussian random ﬁelds (according to the random process model of
surface roughness 61 ), then each value of h ̃ (q) should be a complex
number that has random real and imaginary components distributed
according to a Gaussian distribution. Therefore, C(q) should be
distributed according to a χ 2 -distribution with 2 degrees of freedom,
i.e., an exponential distribution. Therefore, the maximum likelihood
estimator for the true value of C(q) at each value of q is the arithmetic
average of all individual measurements at that q.

Arithmetic average, not geometric average (what would result from arithmetic mean on log scale).

**Comment by mcrot** [comment]
We agreed not to display errors in the plot. Should standard errors be part of the downloaded data, @pastewka ?

**Comment by pastewka** [comment]
Yes, they can be part of the downloaded data


________________________________
Von: Michael Röttger <notifications@github.com>
Gesendet: Dienstag, 2. März 2021 16:06
An: ComputationalMechanics/TopoBank
Cc: Lars Pastewka; Mention
Betreff: Re: [ComputationalMechanics/TopoBank] Average data in analysis plot (#365)

**Comment by mcrot** [comment]
Hm - after a discussion with @AntoineSIMTEK  I've understood that the standard error of the average should be empty/masked/NAN for sampling points with only one contributing measurement. The function `scipy.stats.sem` uses a 
masked array to mask those values which is a good solution, I think. So the analysis result for the standard error is a masked array.

Since we agreed to include the standard error in the download files, I have the following question:
How to represent these masked values in the TXT and XLSX files?

Suggestion:
- empty cell in XLSX (which is default)
- a dash ("-") in TXT files  (or NAN?)
- we could add a column which shows the number of measurements contributing to each point

What do you think @pastewka and @AntoineSIMTEK ?

**Comment by mcrot** [comment]
Currently I've this solution, calculated for the example surface (_Jacobs, Tevis D. B., Till Junge, and Lars Pastewka. 2017. “Quantitative Characterization of Surface Topography Using Spectral Analysis.”_ ):
[Power_Spectrum.txt](https://github.com/ComputationalMechanics/TopoBank/files/6115820/Power_Spectrum.txt)
[Power_Spectrum.xlsx](https://github.com/ComputationalMechanics/TopoBank/files/6115824/Power_Spectrum.xlsx)

- empty cell in XLSX
- "nan" in TXT file (was easier)
 
Could have a look at the files whether the results are making sense?

![grafik](https://user-images.githubusercontent.com/9113541/110631670-0ea2bd80-81a7-11eb-9a1a-04b20aa103c4.png)

**Comment by mcrot** [comment]
Thanks for the feedback, I'll add comments to the files.

Yes, it's logarithmic bin spacing. In the example, we have 100 sampling points:
![grafik](https://user-images.githubusercontent.com/9113541/110760008-8972e380-824e-11eb-8cae-0c8c8b0b5f72.png)

**Comment by mcrot** [comment]
For the bin spacing, I use the Python function `numpy.geomspace`, e.g.
```
In [3]: np.geomspace(0.1,7,15)
Out[3]: 
array([0.1       , 0.13545428, 0.18347861, 0.24852962, 0.33664399,
       0.45599868, 0.61766971, 0.83666003, 1.13329178, 1.53509216,
       2.07934796, 2.81656572, 3.81515868, 5.16779554, 7.        ])
```

I would like to use exactly the same averaging procedure also for ACF and Variable Bandwidth. For ACF sometimes the
first distance value is zero, which is not allowed as argument for `np.geomspace`. 

In the code used for averaging I would just exclude all x values smaller or equal zero.
So the average ACF will only include distances > 0. Do you have any concerns, @pastewka and @tdbjacobs ?
Or should I include special values for zero?
I think it's okay to just exclude zero from the average - let me know if you think this should be done differently.

**Comment by pastewka** [comment]
Yes, this sounds good. The ACF at distance 0 is 0 anyway. Just show data points larger than 0. The VBM should not have data at 0.

**Comment by mcrot** [comment]
Ah yes :-)

**Comment by tdbjacobs** [comment]
makes sense.

(for the PSD, there will be a non-zero value at q=0, and the value is
meaningful, but this cannot be displayed on a log-log plot.)

-Tevis


Tevis Jacobs
William Kepler Whiteford Faculty Fellow and Associate Professor
Mechanical Engineering and Materials Science
University of Pittsburgh
http://www.engineering.pitt.edu/JacobsLab/
Mail: 636 Benedum Hall, 3700 O'Hara St., Pittsburgh, PA 15261
Office: 538-E Benedum Hall, 412-624-9736
***@***.***

**Comment by pastewka** [comment]
I agree, but that value is essentially the rms height which can be obtained from other means.

**Comment by pastewka** [comment]
Sorry, it's of course not the rms height but the mean value to some power - which should be zero since it is always subtracted.

**Comment by mcrot** [comment]
Ok, merged in develop branch.
